fix: update environment variable handling to use am.env for application manifest path

diff --git a/.github/actions/app-manifest/action.yaml b/.github/actions/app-manifest/action.yaml
--- a/.github/actions/app-manifest/action.yaml
+++ b/.github/actions/app-manifest/action.yaml
@@ -67,8 +67,15 @@ runs:
           $([[ -n "${{ inputs.version }}" ]] && echo "--version ${{ inputs.version }}") \
           $([[ -n "${{ inputs.name }}" ]] && echo "--name ${{ inputs.name }}") \
           $([[ -n "${{ inputs.meta-data-files }}" ]] && echo "${{ inputs.meta-data-files }}")
-          echo "PATH_APP_MANIFEST=$([[ -n '${{ inputs.output }}' ]] && echo '${{ inputs.output }}' || echo ${PATH_APP_MANIFEST})"
-          echo "PATH_APP_MANIFEST=$([[ -n '${{ inputs.output }}' ]] && echo '${{ inputs.output }}' || echo ${PATH_APP_MANIFEST})" >> $GITHUB_OUTPUT
+          if [[ -f "am.env" ]]; then
+            echo "Sourcing am.env file"
+            source am.env
+          else
+            echo "am.env file not found"
+          fi
+          echo "Generated application manifest path: $PATH_APP_MANIFEST"
+          # echo "PATH_APP_MANIFEST=$([[ -n '${{ inputs.output }}' ]] && echo '${{ inputs.output }}' || echo ${PATH_APP_MANIFEST})"
+          echo "PATH_APP_MANIFEST=${PATH_APP_MANIFEST}" >> $GITHUB_OUTPUT
       shell: bash
     - name: "Upload application manifest"
       if: ${{ always() && steps.generate_app_manifest.outputs.PATH_APP_MANIFEST }}
